### ISSUE TITLE
Add a TMX parser

### ISSUE THREAD

**Issue by Volcyy** [strinking/strikemon#1]
Since we're going to create our maps using the [Tiled](http://www.mapeditor.org), we need a way to go from [TMX Map Format](http://doc.mapeditor.org/reference/tmx-map-format/) -> our code. For this, we need a TMX parser. To finally put my C++ """skills""" to good use, I would like to work on this 👋 

Some resources:
- [Tiled Map Editor Website](http://www.mapeditor.org)
- [TMX Map Format Documentation](http://doc.mapeditor.org/reference/tmx-map-format/)
- [pugixml (XML Parser)](http://pugixml.org)
- [pugixml quick start guide](http://pugixml.org/docs/quickstart.html)

**Comment by invghost** [comment]
Added in 1ab6639 and used in 205defe.
